name: Build Windows Executable
description: Run the Windows build script to compile the project
runs:
  using: "composite"
  steps:
    - name: Run Windows build script
      run: scripts\\build_windows.bat
      shell: pwsh
