name: Install Tools
description: Install Python, Conan, and CMake for the build environment
runs:
  using: "composite" # Composite actions allow you to collect a series of workflow job steps into a single action which you can then run as a single job step in multiple workflows. 
  steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Conan package manager
      run: |
        python -m pip install --upgrade pip
        pip install conan
        conan --version

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.28.0'
