name: Publish GitHub Release
description: Create a GitHub release and attach Windows/Linux build artifacts
runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: Publish release on GitHub
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
        files: artifacts/**/*.{zip,tar.gz}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

