name: Publish GitHub Release
description: Create a GitHub release and attach Windows/Linux build artifacts

inputs:
  github_token:
    description: "GitHub token used to authenticate release publishing"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: Publish release on GitHub
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
        files: |
          artifacts/**/*.zip
          artifacts/**/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
